USE [master]
GO

/****** Object:  Database [user_PB]    Script Date: 22.03.2024 9:19:21 ******/
CREATE DATABASE [user_PB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'user_PB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\user_PB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'user_PB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\user_PB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [user_PB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [user_PB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [user_PB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [user_PB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [user_PB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [user_PB] SET ARITHABORT OFF 
GO

ALTER DATABASE [user_PB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [user_PB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [user_PB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [user_PB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [user_PB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [user_PB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [user_PB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [user_PB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [user_PB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [user_PB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [user_PB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [user_PB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [user_PB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [user_PB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [user_PB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [user_PB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [user_PB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [user_PB] SET RECOVERY FULL 
GO

ALTER DATABASE [user_PB] SET  MULTI_USER 
GO

ALTER DATABASE [user_PB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [user_PB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [user_PB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [user_PB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [user_PB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [user_PB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [user_PB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [user_PB] SET  READ_WRITE 
GO


